# Run zsh via antigen
source ~/.antigen.zsh

source ~/dotfiles/zsh/aliases
source ~/dotfiles/zsh/functions
source ~/dotfiles/zsh/exports

# Load the work aliases or other stuff
WORK_STUFF=$HOME/.work
if [ -f "$WORK_STUFF" ]; then
  source $WORK_STUFF
fi


# Load the oh-my-zsh's library.
antigen use oh-my-zsh

# Bundles from the default repo (robbyrussell's oh-my-zsh).
antigen bundle git
antigen bundle pip
antigen bundle common-aliases
antigen bundle docker-compose
antigen bundle docker-machine
antigen bundle command-not-found

# Syntax highlighting bundle.
antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle zsh-users/zsh-autosuggestions
antigen bundle zsh-users/zsh-completions
antigen bundle akarzim/zsh-docker-aliases

# Load the theme.
antigen theme https://github.com/yupswing/yupgnoster.git yupgnoster

# Tell Antigen that you're done.
antigen apply

# bindings
bindkey "[D" backward-word
bindkey "[C" forward-word

clear

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
